# Generated by Django 4.1.2 on 2022-10-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
